### PR TITLE
Icon-Redesign

### PR DESCRIPTION
**Pull request by Fatih20**
The previous icon doesn't comply by the [eOS HIG](https://elementary.io/docs/human-interface-guidelines#contrast) regarding outlines, contrast, shadows, and pictogram placement. Also, it doesn't look like an eOS-esque icon that has skeuomorphic but simplistic look.

### CODE REVIEW

**Comment by bcedu** [comment]
I want to change the icon, the current one was only temporal. But I would like the new one to be something like the folder icon from elementary (the icon of "files" app) with the google drive logo inside instead of the home logo.

What do you think?

**Comment by Fatih20** [comment]
I think it's not a good idea to use the files icon from the original eOS icon set because they are built with different intention. 
Also, just slapping a google drive logo to an existing icon makes it look 

1. Cluttered, therefore hard to see in smaller sizes, doesn't comply by [eOS HIG](https://elementary.io/docs/human-interface-guidelines#size) about visibility in all sizes.
2. Amateur-ish

**Comment by bcedu** [comment]
I don't think it looks amateur if it's well done. Also, what can follow the elementary style guides more than the elementary files icon itself?

**Comment by bcedu** [comment]
I listen to new possible designts, but i dont really like the design that you have done in this PR

**Comment by Fatih20** [comment]
Give me the reason why the current icon is bad? Because it's not literal? Icon is supposed to be a metaphor, this is **not** coding where you label every function as what EXACTLY it does. 

Also, no, just copying the eOS icon doesn't suddenly make you icon eOS compliant, there are rules regarding the placement of pictogram since what you want to do is simply slapping a Gdrive icon on top of the files icon which, by the way, violated the 2 points out of 5 regarding [Dos and Don'ts](https://elementary.io/docs/human-interface-guidelines#dos-donts)

> Your icon should not be overly complicated. Keep in mind that since there are smaller sizes, the elements that make up your icon should be distinguishable when at those sizes.
> Avoid simply slapping an element onto a base shape; use a unique outline to make your icon more distinct.
Have you actually downloaded your own apps from the appcenter and look how 

1. you need to squint your eyes to see what the apps icon represents in the application dropdown menu? I do this despite using a 24 inch QHD monitor.
2. out of place it looked like if you put them next to other eOS icons?

**Comment by Fatih20** [comment]
Okay, do you have objective reasons why "cloud shape bad"? The [eOS HIG](https://elementary.io/docs/human-interface-guidelines#design-philosophy) specifies that design is not subjective.

And, again, the icon doesn't have to be literal. Anyone who has downloaded the apps has read what the app is for and so, doesn't need to be told what the app does **every single time** they open or search for the app. Just need to have a rough representation of it.

**Comment by bcedu** [comment]
I know that design is not only subjective, it has a goal. But I'm sure that there are other icons apart from this one that also acomplish the goal. 

So, I'm just saying that I would like another design, that also acomplish the goal, different from this one  (because I don't like it, and I think that the creator of the app has something to say about its icon).

And what I would like is an icon that shows in some way the logo from google drive.

**Comment by Fatih20** [comment]
Alright, then. Let me change your mind on why putting a google drive logo on this app is a bad idea.

1. Very thin but possible potential for Google to sue on the basis of copyright infringement
2. You're essentially helping Google market its product by using the Gdrive logo, why would you want to be a free promoter of a product made by a multi-billion multi-national company?
3. Your app doesn't feel distinct. It would feel like any other generic Gdrive client. By using a different logo, it would make your app, while still being a Gdrive client, a more distinct first impression by user who found it through something other than the appcenter.

**Comment by bcedu** [comment]
Mmh.. You are right with the copyright point.

What do you thinc about an icon formed by a folder icon and inside the folder with your logo (or some variation of it, as you like). I would like to mantain the idea of the fokder because the app acctually creats a folder and update the files of this folder

**Comment by Fatih20** [comment]
It could be done.

**Pull request merged**
